name:                PROJECTNAME
version:             0.0.0.0
github:              GITHUB
license:             BSD3
author:              AUTHOR
maintainer:          MAINTAINER
copyright:           COPYRIGHT

extra-source-files:
- README.md
- ChangeLog.md

description:         DESCRIPTION

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
- base >= 4.10 && < 10
- aeson >=0.6 && <1.3
- bcrypt >= 0.0.8 && < 0.0.12
- bytestring >=0.9 && <0.11
- case-insensitive
- classy-prelude >=1.4 && <1.5
- classy-prelude-conduit >=1.4 && <1.5
- classy-prelude-yesod >=1.4 && <1.5
- conduit >=1.0 && <2.0
- containers
- data-default
- directory >=1.1 && <1.4
- errors
- esqueleto >= 2.5 && < 2.7
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- hjsmin >=0.1 && <0.3
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- persistent >=2.8 && <2.9
- persistent-postgresql >=2.8 && <2.9
- persistent-template >=2.5 && <2.9
- rio >= 0.1.1.0
- safe
- shakespeare >=2.0 && <2.1
- template-haskell
- text >=0.11 && <2.0
- transformers
- time
- unordered-containers
- vector
- wai
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.3
- yaml >=0.8 && <0.9
- yesod >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- yesod-static >=1.6 && <1.7

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  PROJECTNAME-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - PROJECTNAME
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  PROJECTNAME-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - PROJECTNAME
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
